# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Ürün Adı')),
                ('name_en', models.CharField(blank=True, max_length=140, null=True, verbose_name='Ürün Adı')),
                ('name_tr', models.CharField(blank=True, max_length=140, null=True, verbose_name='Ürün Adı')),
                ('title', models.CharField(blank=True, max_length=140, null=True, verbose_name='Ürün Başlığı')),
                ('title_en', models.CharField(blank=True, max_length=140, null=True, verbose_name='Ürün Başlığı')),
                ('title_tr', models.CharField(blank=True, max_length=140, null=True, verbose_name='Ürün Başlığı')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ürün Fiyatı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ('-created_at',),
            },
        ),
    ]
